### ISSUE TITLE
Contribuição com a Disciplina de Teste - BDD

### ISSUE THREAD

**Issue by ZeckCarvalhos** [TS-puc-20201/Teste-De-Software#1]
Gostaria de deixar minha contribuição para a disciplina com uma apresentação referente ao BDD, encontra-se no arquivo abaixo:

[Apresentação BDD.pdf](https://github.com/lesandropcodes/Teste-De-Software/files/4696144/Apresentacao.BDD.pdf)

Tentei adicionar em uma nova branch e solicitar o pull request, entretanto a permissão remota foi negada ao meu usuário.

**Comment by lesandrop** [comment]
Obrigado. A apresentação foi preparada por você? Se sim, coloque o seu nome nela, poste em https://speakerdeck.com/ e me mande aqui o link que vou acrescentar nos links recomendados para os futuros alunos. Para o próximo semestre, eu pretendo incluir uma aula sobre esse tópico.

**Comment by ZeckCarvalhos** [comment]
Não preparei ela inicialmente, fiz uma adaptação da apresentação original que foi realizada na empresa. Removendo algumas informações técnicas dos projetos para ser possível a distribuição, com a devida autorização.

**Comment by lesandropcodes** [comment]
Obrigado. Eu adicionei à lista de materiais adicionais da disciplina https://github.com/lesandropcodes/Teste-De-Software/blob/master/00a-MaterialOnline/Links-TextAndCodes.md. Farei uma atividade com BDD neste semestre e esse material será bastante útil.
